### ISSUE TITLE
Need help debugginh

### ISSUE THREAD

**Issue by alpha-256** [alpha-256/Python-Statistical-Evolution-Simulator-PySES#3]
Need help debugging
[code: here](https://github.com/alpha-256/Python-Statistical-Evolution-Simulator-PySES/issues)

**Comment by sm79637413** [comment]
Pushed some code, please check it.
Edit:
Please also put some test cases, so I can test it as before pushing onto master

**Comment by alpha-256** [comment]
problem solved
closing issue
