### ISSUE TITLE
Debug help required

### ISSUE THREAD

**Issue by alpha-256** [alpha-256/Python-Statistical-Evolution-Simulator-PySES#4]
https://github.com/alpha-256/Python-Statistical-Evolution-Simulator-PySES/blob/master/Tools/Word%20Checker/wordfreq1.py

**Comment by sm79637413** [comment]
"Debug help" granted
https://github.com/alpha-256/Python-Statistical-Evolution-Simulator-PySES/blob/master/Tools/Word%20Checker/wordfreq1.py
